### ISSUE TITLE
Support - refused to connect

### ISSUE THREAD

**Issue by Luna-devv** [is-a-dev/register#1610] opened 2022-01-23 19:19 UTC
Your domain name:
Luna Seemann

When I go to [`luna.is-a.dev`](https://luna.is-a.dev/) I get the error "`refused to connect`". I checked and the IP in the A record is correct. I've even logged all events/requests in my proxy manager and I get the events logged when I go to [`51.161.24.80:3040`](http://51.161.24.80:3040) or [`waya.one`](https://waya.one) but not when I go to [`luna.is-a.dev`](https://luna.is-a.dev/) I don't see anything in the logs as you can see in the video linked bellow. Maybe you know why and know how to fix this. Thank you
My pull request with the configuration: https://github.com/is-a-dev/register/pull/1583/commits/c12ae5a24369deb7723aa1e8f3ffcdc98b3be448

Video: https://cdn.waya.one/1642965213.mp4

Proxy manager configuration: 
<br />
![image](https://user-images.githubusercontent.com/71079641/150694678-982385f5-9e51-48c5-8bd0-b305d26f6019.png)
<br />
![image](https://user-images.githubusercontent.com/71079641/150694729-76dd6154-5c2a-45c0-b6c8-a884877a9bfe.png)

**Comment by phenax** [comment] 2022-01-24 13:31
This seems to be working fine now. Network propogation can take some time in certain cases which could be the cause. It usually happens in a minute but in worst cases, it could take upto a day. Closing this issue.

**Closed by phenax** 2022-01-24 13:31 UTC
Labels: support
