### ISSUE TITLE
New Namecheap record limits

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [is-a-dev/register#9707] opened 2023-11-29 11:03 UTC
~~Recently, Namecheap [announced a new DNS record limit of 150](https://www.namecheap.com/support/knowledgebase/article.aspx/10058/10/namecheap-dns-limits) on their DNS service; which is-a.dev uses.~~ According to Phenax, it seems to be an issue with cPanel.

This is why records are not being updated or created, however deleting records should still work.
We are currently in communication to attempt to get this limit lifted or increased for us as we cannot operate with this limit due to the amount of DNS records we have. *We do have other methods of solving this issue if they do not increase our record limit.*

## NO PULL REQUESTS WILL BE MERGED UNTIL THIS IS SOLVED
Domain deletion or non-domain related pull requests will still be reviewed.

### Updates will be posted here.

**Comment by phenax** [comment] 2023-11-29 12:53
It's been 150 on namecheap for a while now. The article was last updated in 2021 so it's not recent. We use namecheap with cpanel's zone management for the DNS records. There's no limit to dns records there.

If new records aren't being created, that would be an unrelated issue that we need to address. Sometimes an invalid dns update can clog things up which has happened once before. I'll take a look.

**Comment by phenax** [comment] 2023-11-29 14:56
@is-a-dev/maintainers, could someone add examples of the records here that are not being updated/added so we can verify if the problem is fixed?

**Comment by andrewstech** [comment] 2023-11-29 18:45
@phenax trung.is-a.dev there is also others but I'm struggling to find the messages. Also check these logs there is some error on adding/removing records.

https://github.com/is-a-dev/register/actions/runs/7031214865/job/19132346446

**Comment by WilliamDavidHarrison** [comment] 2023-11-29 21:27
> Maybe we could use Cloudflares DNS? They seem to have a pretty good api. Or something like bunny.net

Migration to Cloudflare would be slightly annoying due to the amount of records we have.

**Comment by phenax** [comment] 2023-11-30 07:53
> trung.is-a.dev
@andrewstech, it seems to be working now. It was as I expected an invalid record update that caused it. I'll see if I can find how this happened in the first place.

There is another issue with the `gattinhosbot.json` record where the `\` character in txt records seems to be removed when the record is published upstream. Looking into that as well.

Other than that, let me know if there are any other records that aren't getting pushed. If not, we can close this issue.


> Maybe we could use Cloudflares DNS? They seem to have a pretty good api. Or something like bunny.net

We had considered cloudflare in the past but unfortunately it has a limit on number of dns records unless you are on the enterprise plan. Any service with a hard limit would be a problem since we don't want to keep migrating from one dns backend to another when we reach their limit.

**Comment by daanschenkel** [comment] 2023-11-30 08:12
Maybe bunny.net?

Op do 30 nov. 2023 08:53 schreef Akshay Nair ***@***.***>:

**Comment by daanschenkel** [comment] 2023-11-30 08:15
Oh this is cool https://docs.bunny.net/docs/getting-started

**Closed** 2023-11-30 09:19 UTC
Labels: bug, wip, maintainer
