### ISSUE TITLE
The Website is down!!!

### ISSUE THREAD

**Issue by Nalin-2005** [is-a-dev/register#612] opened 2021-03-08 13:04 UTC
The Website is down!!!

**Comment by phenax** [comment] 2021-03-08 18:06
@Nalin-2005. What was the exact error you faced? I'm unable to find any dips in the logs.

**Comment by Nalin-2005** [comment] 2021-03-09 03:50
It's fine now but the error shown at that time was "is-a.dev took too long to respond". I think this would not show in the logs that's why you could not do anything. Try using [uptimerobot](uptimerobot.com), that alerts you whenever your website is down.

**Comment by Nalin-2005** [comment] 2021-03-09 03:51
The issue was not just with the root domain but also with all the subdomains

**Comment by phenax** [comment] 2021-03-10 10:09
@Nalin-2005. Thanks for the suggestion! I've setup better monitoring for the subdomains so it'll be easier to identify the root cause. Closing this issue as there are no action points at the moment.

**Closed by phenax** 2021-03-10 10:09 UTC
Labels: bug
