### ISSUE TITLE
LyraStudios Marked for Phishing by Google Safe Browsing

### ISSUE THREAD

**Issue by VaibhavSys** [is-a-dev/register#8172] opened 2023-09-24 11:10 UTC
Domain you want to report: adev.is-a.dev -> lyrastudios.github.io

### Reason
This domain is marked by Google Safe Browsing for Phishing. https://github.com/LyraStudios/LyraStudios.github.io may be the repository serving the contents of this domain.
From its readme:

> Lyra studios is one of the best modern unblocked game sites. Check it out [here](https://lyrastudios.github.io/). If this link is blocked, you can get more links in our [Discord Server!](https://dsc.gg/lyragamesbruh)

It mentions that it is a unblocked game sites, I think it may be related to piracy too. And it also mentions "if the link is blocked", which means that the site owner expects the link to be flagged by Google Safe Browsing and other systems. I have no solid evidence but this was suspicious so I decided to submit a report.

![image](https://github.com/is-a-dev/register/assets/76240678/7e94a310-eeed-4398-ba02-91f831f5de1d)

**Comment by WilliamDavidHarrison** [comment] 2023-09-24 11:13
We do not generally allow unblocked games sites, I think we should remove this domain.

**Comment by VaibhavSys** [comment] 2023-09-24 11:19
> We do not generally allow unblocked games sites, I think we should remove this domain.

I am much more concerned about it being a phishing site, which Google Safe Browsing flagged it for.

**Comment by WilliamDavidHarrison** [comment] 2023-09-24 11:20
I've taken a look at the source code and it does not seem to look very legit and also considering Google Safe Browsing has flagged it is not a good indicator. This domain will be removed @NotJack173.

**Comment by WilliamDavidHarrison** [comment] 2023-09-24 11:22
The domain has been removed, I will keep this issue open for 48 hours if @NotJack173 wants to discuss this.

**Comment by NotJack173** [comment] 2023-09-24 15:32
Wdym it doesn’t look very legit?, I’m not the best at coding and I’m still trying to learn :(

**Comment by NotJack173** [comment] 2023-09-24 15:33
> > We do not generally allow unblocked games sites, I think we should remove this domain.
> 
> I am much more concerned about it being a phishing site, which Google Safe Browsing flagged it for.

Idk why google flagged it but check the code and js we don’t phish

**Comment by NotJack173** [comment] 2023-09-24 15:33
May be because we had a swf file for some games

**Comment by WilliamDavidHarrison** [comment] 2023-09-24 22:54
> Wdym it doesn’t look very legit?, I’m not the best at coding and I’m still trying to learn :(

The files and obfuscated scripts are quite suspicious to us.

**Comment by zkayns** [comment] 2023-09-24 23:25
> May be because we had a swf file for some games

As a Google employee, I can confirm we mark all pages using .swf files as phishing.

**Comment by WilliamDavidHarrison** [comment] 2023-09-25 04:19
> As a Google employee, I can confirm we mark all pages using .swf files as phishing.

If Google Safe Browsing does flag `.swf` files as phishing, @NotJack173 will need to remove them, even if they are not used for phishing. This is because it could cause a bad reputation for the is-a.dev domain as a whole which is not good. Also, may I ask, why is there a lot of obfuscated JavaScript code on the website? That is quite suspicious.

**Comment by NotJack173** [comment] 2023-09-28 17:14
> > May be because we had a swf file for some games
> 
> 
> 
> As a Google employee, I can confirm we mark all pages using .swf files as phishing.

How do I stop that?
I want to add binding of Isaac but it uses swf files

**Comment by WilliamDavidHarrison** [comment] 2023-09-28 23:10
@NotJack173 What is your website actually for?

**Comment by DiamondBroPlayz** [comment] 2023-10-02 23:01
Owner has pirated games on his website.

> https://lyra-studios.vercel.app/assets/games/mc15
> https://lyra-studios.vercel.app/assets/games/mc18

These are called Eaglercraft and are cracked versions of Minecraft compiled for the web. I wouldn't usually care because these are old versions, but this service shouldn't be used for that sort of thing

**Comment by WilliamDavidHarrison** [comment] 2023-10-03 04:46
I will close this issue and this domain will not return. There is overwhelming evidence that this website is abusing their is-a.dev subdomain.

**Closed by WilliamDavidHarrison** 2023-10-03 04:46 UTC
Labels: report-abuse, status: awaiting user response
